modelo/bolsa/urls.py
from django.conf.urls import url, include
from django.views.i18n import JavaScriptCatalog

from modelo.bolsa.views import planodecontas_list, simple_upload, planodecontas_export

app_name = 'bolsa'

urlpatterns = [
    url(r'planodecontas/listar/$', planodecontas_list, name='planodecontas_list'),

    url(r'planodecontas/importar/$', simple_upload, name='simple_upload'),
    url(r'planodecontas/exportar/$', planodecontas_export, name='planodecontas_export'),

    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

modelo/urls.py
""" modelo URL Configuration """

from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^bolsa/', include('modelo.bolsa.urls', namespace='modelo-bolsa')),
    url(r'^bookings/', include('modelo.bookings.urls', namespace='modelo-bookings')),
    url(r'^api/bookings/', include('modelo.bookings.api.urls', namespace='booking-api')),
    path('admin/', admin.site.urls),
]

modelo/bolsa/models.py
from django.db import models
#DATA-PAPEL-OP(COMPRA.VENDA,DIVIDENDOS,SPLIT), QTD, CUSTO TOTAL(CORRETAGEM+IMPOSTOS)
# Create your models here.

#0.00.00.00.00.00.0000-0
class PlanoDeContas(models.Model):
    classification = models.CharField('Classificação', primary_key=True, max_length=100)
    name = models.CharField('Descrição', max_length=100)
    reduced_account = models.CharField('Conta reduzida', max_length=100)
    sn = models.CharField('SN', max_length=100)
    n = models.CharField('N', max_length=5)
    source = models.CharField('Origem', max_length=100)
    account_type = models.CharField('Tipo Conta', max_length=8)

modelo/bolsa/forms.py
from django import forms


class FileUploadForm(forms.Form):
    """File upload form."""
    excelfile = forms.FileField(required=True)

modelo/bolsa/views.py
# Create your views here.
from modelo.bolsa.models import PlanoDeContas

from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render

import xlrd


def simple_upload(request):
    if request.FILES:
        print(request.POST, 'POST')
        print(request.FILES, 'FILES')
        print(request.FILES['file'], 'FILES.file')

    if request.method == 'POST' and request.FILES['file']:
        myfile = request.FILES['file']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        #uploaded_file_url = fs.url(filename)
        filepath = fs.path(myfile.name)

        importaPlanilha(filepath)

        # return HttpResponseRedirect('/bolsa/planodecontas/listar/')
        # como é feito um ajax, não adianta o usar o redirect do django.
        # vc pode retornar um json como esse e chegar no JS se tudo ocorreu bem e assim
        # redirecionar com JS
        return JsonResponse({'statuss': 'success', 'names': 'vitor'})
    return render(request, 'import_form.html')

# def simple_upload(request):
#     if request.method == 'POST' and request.FILES:
#         myfile = request.FILES
#         fs = FileSystemStorage()
#         filename = fs.save(myfile, myfile)
#         #uploaded_file_url = fs.url(filename)
#         dir = fs.path(myfile)
#
#         importaPlanilha(dir)
#
#         return HttpResponseRedirect('/bolsa/planodecontas/listar/')
#
#     return render(request, 'import_form.html')

def remove(field):
    a = str(field)

    if a[len(a) - 2:] == '.0':
        a = a[:len(a) - 2]
    else:
        a = a.replace("-", "").replace(".", "")

    return a



def importaPlanilha(dir):
    #Funcionacom *.xls e *.xlsx

    workbook = xlrd.open_workbook(dir)
    #workbook = xlrd.open_workbook("/home/eliaspai/Área de Trabalho/MODELO_PLANO_DE_CONTAS_PARA_IMPORTAR.xlsx")

    # Posso usar sheet_by_name("Name") ou sheet_by_index(0, 1, 2, ..., N)
    #worksheet = workbook.sheet_by_name("Plan1")
    worksheet = workbook.sheet_by_index(0)

    lista = []

    #print(worksheet.nrows)
    for r in range(1, worksheet.nrows):
        lista.append(
            PlanoDeContas(classification=remove(str(worksheet.cell(r, 0).value)),
                          name=remove(str(worksheet.cell(r, 1).value)),
                          reduced_account=remove(str(worksheet.cell(r, 2).value)),
                          account_type=remove(str(worksheet.cell(r, 4).value)),
                          source=remove(str(worksheet.cell(r, 3).value)),

                          )
        )

    PlanoDeContas.objects.bulk_create(lista)
    return HttpResponseRedirect('/bolsa/planodecontas/listar/')


def planodecontas_list(request):
    q = request.GET.get('searchInput')
    print(request.GET)
    if q:
        print(q)
        planodecontas = PlanoDeContas.objects.filter(name__icontains=q)
    else:
        planodecontas = PlanoDeContas.objects.all()
    context = {'planodecontas': planodecontas}
    print(context)
    return render(request, 'bolsa_list.html', context)


def planodecontas_export(request):
    response = HttpResponse(content_type='text/plain')
    response['Content-Disposition'] = 'attachment; filename="PlanoDeContas.txt"'

    planodecontas = PlanoDeContas.objects.all()

    #writer = response

    for planodecontas_obj in planodecontas:
        response.write(planodecontas_obj.classification + ' ' * (30 - len(planodecontas_obj.classification))
                   + ' ' * (30)
                   + planodecontas_obj.reduced_account + ' ' * (10 - len(planodecontas_obj.reduced_account))
                   + planodecontas_obj.account_type[:1]
                   + planodecontas_obj.name[:50] + ' ' * (50 - len(planodecontas_obj.name[:50]))
                   + planodecontas_obj.source[:1] + ' ' * (1 - len(planodecontas_obj.source[:1]))
                   + "INN"
                   + ' ' * (15)
                   + ' ' * (15)
                   + '0' * (10)
                   + "N"
                   + ' ' * (10)
                   + "NNN"
                   + ' ' * (50)
                   + ' ' * (15)
                   + "NN"
                   + '0' * (10)
                   + ' ' * (30)
                   + '0' * (10)
                   + ' ' * (12)
                   + ' ' * (10)
                   + ' ' * (30)
                   + ' ' * (30)
                   + ' ' * (20)
                   + "\n")

    return response

modelo/bolsa/templates/bolsa_list.html
{% extends "index.html" %}

{% block content %}
        <!-- BEGIN SEARCH BAR -->
        <div class="card-body style-primary no-y-padding">
            <form class="form form-inverse">
                <div class="form-group">
                    <div class="input-group input-group-lg">
                        <div class="input-group-content">
                            <input type="text" class="form-control" id="searchInput" name="searchInput" placeholder="Enter your search here">
                            <div class="form-control-line"></div>
                        </div>
                        <div class="input-group-btn">
                            <button class="btn btn-floating-action btn-default-bright" type="button"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </div><!--end .form-group -->
            </form>
        </div><!--end .card-body -->
        <!-- END SEARCH BAR -->

        <!-- BEGIN RESPONSIVE TABLE 2 -->
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body no-padding">
                        <div class="table-responsive no-margin">
                            <table class="table table-striped no-margin">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Classificação</th>
                                        <!--<th>N.Classificação</th>-->
                                        <th>Descrição</th>
                                        <th>Cód.</th>
                                        <!--<th>SN</th>-->
                                        <!--<th>N</th>-->
                                        <th>Origem</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for conta in planodecontas %}
                                        <tr>
                                            <!--<td>-->
                                                <!--<a href="{{ conta.get_absolute_url }}">{{ conta.classification|linebreaks }}</a>-->
                                            <!--</td>-->
                                            <td></td>
                                            <td>{{ conta.classification|linebreaks }}</td>
                                            <td>{{ conta.name|linebreaks }}</td>
                                            <td>{{ conta.reduced_account|linebreaks }}</td>
                                            <!--<td>{{ conta.sn|linebreaks }}</td>-->
                                            <!--<td>{{ conta.n|linebreaks }}</td>-->
                                            <!--<td>{{ conta.source|linebreaks }}</td>-->
                                            <td>{{ conta.account_type|linebreaks }}</td>

                                        </tr>
                                    {% empty %}
                                        <li>
                                            Sem registros
                                        </li>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div><!--end .table-responsive -->
                    </div><!--end .card-body -->
                </div><!--end .card -->
            </div><!--end .col -->
        </div><!--end .row -->
        <!-- END RESPONSIVE TABLE 1 -->
{% endblock %}

modelo/bolsa/templates/import_form.html
{% extends "index.html" %}

{% block content %}
        <!-- BEGIN FILE UPLOAD -->
        <div class="row">
            <div class="col-lg-offset-1 col-md-10">
                <div class="card">
                    <div class="card-head style-primary">
                        <header>Planilha com Plano de Contas em Excel (*.xls e *.xlsx)</header>
                    </div>
                    <div class="card-body no-padding">
                        <form method="post" action="{% url 'bolsa:simple_upload'  %}" class="dropzone" id="my-awesome-dropzone" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="dz-message">
                                <h3>Solte os arquivos aqui ou clique para fazer o upload.</h3>
                                <em>(Apesar de aceitar, ainda não trabalhamos com múltiplos arquivos <strong>portanto</strong> escolha apenas um.)</em>
                            </div>
                        </form>
                    </div><!--end .card-body -->
                </div><!--end .card -->
                <em class="text-caption">Dropzone file upload</em>
            </div><!--end .col -->
        </div><!--end .row -->
        <!-- END FILE UPLOAD -->
{% endblock %}

{% block extrajs %}
<script>
(function($) {
    Dropzone.options.myAwesomeDropzone = {
        init: function() {
            var myDropzone = this;
            myDropzone.on("success", function(data) {
                // esse data contem alguns dados do arquivo, nome, tamanho, procentagem enviada, etc, e um dos campos STATUS parece indicar se tudo ocorreu bem.
                // tem o campo XHR e nele tem o RESPONSE que contem dados retornados pela view.py, caso vc queira fazer alguma checagem, sei lá. dá uma olhada pra ver o que vc acha.
                console.log(data['status']);
                if (data['status'] == 'success'){
                    location.href = '/bolsa/planodecontas/listar/';
                }
              });
        }
    };
})(jQuery);
</script>
{% endblock extrajs %}

modelo/bolsa/templates/import_form_backup.html
<!--INCLUINDO O FORM FICA LEGAL E SEM FUNCIONAR, RETIRANDO FICA FEIO EM FUNCIONANDO-->
{% extends "account/base.html" %}
<!--{% load static %}-->


<!--{% include 'material/includes/material_css.html' %}
<script src="{% static 'material/js/jquery.js' %}"></script>
{% include 'material/includes/material_js.html' %}-->


{% load material_form %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Agendamento" %}{% endblock %}

{% block inner %}

  <form action="{% url 'bolsa:upload_xls' %}" enctype="multipart/form-data">
    <div class="file-field input-field">
      <div class="btn">
        <span>Arquivo</span>
        <input type="file">
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>

    <a class="waves-effect waves-light btn" type="submit"><i class="material-icons right">cloud</i>Importar</a>
    <button type="submit" name="_submit" class="btn">Importar</button>
  </form>


{% endblock %}